
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestAmazonaws():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_amazonaws(self):
        self.driver.get("https://katalon-test.s3.amazonaws.com/aut/html/form.html")
        self.driver.set_window_size(1936, 1048)
        self.driver.find_element(By.ID, "first-name").click()
        self.driver.find_element(By.ID, "first-name").send_keys("Mr")
        self.driver.find_element(By.ID, "infoForm").click()
        self.driver.find_element(By.ID, "last-name").click()
        self.driver.find_element(By.ID, "last-name").send_keys("MM")
        self.driver.find_element(By.CSS_SELECTOR, ".radio-inline:nth-child(1)").click()
        self.driver.find_element(By.ID, "dob").click()
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .day:nth-child(3)").click()
        self.driver.find_element(By.ID, "address").click()
        self.driver.find_element(By.ID, "address").send_keys("Oshawa")
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("mm@durhamcollege.ca")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("Test")
        self.driver.find_element(By.ID, "company").click()
        self.driver.find_element(By.ID, "company").send_keys("test")
        dropdown = self.driver.find_element(By.ID, "expectation")
        dropdown.find_element(By.XPATH, "//option[. = 'Good teamwork']").click()
        self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(1) > label").click()
        self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(2) > label").click()
        self.driver.find_element(By.CSS_SELECTOR, ".checkbox:nth-child(3) > label").click()
        self.driver.find_element(By.ID, "comment").click()
        self.driver.find_element(By.ID, "comment").send_keys("Test the Application")
        self.driver.find_element(By.ID, "submit").click()

        # **Assertion to verify the success message**
        success_message = WebDriverWait(self.driver, 10).until(
            expected_conditions.visibility_of_element_located((By.ID, "submit-msg"))
        )
        assert success_message.text == "Successfully submitted!", "Success message not displayed!"
    def test_testnonwork(self):
        self.driver.get("https://katalon-test.s3.amazonaws.com/aut/html/form.html")
        self.driver.set_window_size(550, 692)
        self.driver.find_element(By.CSS_SELECTOR, ".radio-inline:nth-child(3) > input").click()
        self.driver.find_element(By.ID, "dob").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-days .datepicker-switch").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".datepicker-months .prev")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".month:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > .day:nth-child(4)").click()
        self.driver.find_element(By.ID, "last-name").click()
        self.driver.find_element(By.ID, "address").click()
        self.driver.find_element(By.ID, "address").send_keys("2")
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("a")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("g")
        self.driver.find_element(By.ID, "company").click()
        self.driver.find_element(By.ID, "company").send_keys("hh")
        self.driver.find_element(By.ID, "submit").click()
        self.driver.execute_script("window.scrollTo(0,0)")
  

